import sqlite3
from pathlib import Path

from alembic import command
from alembic.config import Config

BACKEND_DIR = Path(__file__).resolve().parents[2]


def _config(db_path: Path) -> Config:
    config = Config(BACKEND_DIR / "alembic.ini")
    config.attributes["database_url"] = f"sqlite+aiosqlite:///{db_path}"
    config.attributes["configure_logger"] = False
    return config


def test_upgrade_head_on_fresh_db(tmp_path: Path) -> None:
    db_path = tmp_path / "fresh.db"

    command.upgrade(_config(db_path), "head")

    with sqlite3.connect(db_path) as conn:
        assert conn.execute("SELECT version_num FROM alembic_version").fetchall() == [("0002",)]


def test_alembic_check_reports_no_pending_changes(tmp_path: Path) -> None:
    config = _config(tmp_path / "check.db")
    command.upgrade(config, "head")

    command.check(config)  # raises AutogenerateDiffsDetected on any model/migration drift
