import sqlite3
from pathlib import Path

from alembic import command
from alembic.config import Config

BACKEND_DIR = Path(__file__).resolve().parents[2]


def _config(db_path: Path) -> Config:
    config = Config(BACKEND_DIR / "alembic.ini")
    config.attributes["database_url"] = f"sqlite+aiosqlite:///{db_path}"
    config.attributes["configure_logger"] = False
    return config


def test_upgrade_head_on_fresh_db(tmp_path: Path) -> None:
    db_path = tmp_path / "fresh.db"

    command.upgrade(_config(db_path), "head")

    with sqlite3.connect(db_path) as conn:
        assert conn.execute("SELECT version_num FROM alembic_version").fetchall() == [("0009",)]


def test_alembic_check_reports_no_pending_changes(tmp_path: Path) -> None:
    config = _config(tmp_path / "check.db")
    command.upgrade(config, "head")

    command.check(config)  # raises AutogenerateDiffsDetected on any model/migration drift


def _names(conn: sqlite3.Connection, kind: str) -> set[str]:
    rows = conn.execute("SELECT name FROM sqlite_master WHERE type = ?", (kind,)).fetchall()
    return {name for (name,) in rows}


def test_history_indexes_exist(tmp_path: Path) -> None:
    """§10's job indexes, and the search index's triggers, are all there at head."""
    db_path = tmp_path / "indexes.db"
    command.upgrade(_config(db_path), "head")

    with sqlite3.connect(db_path) as conn:
        assert {
            "ix_jobs_request_id",
            "ix_jobs_created_at",
            "ix_jobs_status",
            "ix_jobs_video_id",
            "ix_requests_created_at",
        } <= _names(conn, "index")
        # A later batch-mode rebuild of `jobs` drops these; this is what notices.
        assert {
            "jobs_fts_insert",
            "jobs_fts_update",
            "jobs_fts_delete",
            "requests_fts_title",
        } <= _names(conn, "trigger")
        assert "jobs_fts" in _names(conn, "table")


def test_0009_backfills_the_search_index(tmp_path: Path) -> None:
    db_path = tmp_path / "backfill.db"
    config = _config(db_path)
    command.upgrade(config, "0008")
    with sqlite3.connect(db_path) as conn:
        conn.execute(
            "INSERT INTO requests (id, media_type, title, options, created_at) "
            "VALUES ('r1', 'tv', 'Some Show', '{}', '2026-09-01 10:00:00')"
        )
        conn.execute(
            "INSERT INTO jobs (id, request_id, url, source_title, episode_title, status, "
            "import_status, step_timings, sidecar_paths, job_dir, created_at, "
            "cancel_requested, attempt, max_attempts, collision_policy, use_cookies, "
            "transcode_fallback_used, import_attempts) VALUES ('j1', 'r1', 'u', "
            "'Uploaded S01E01', 'Pilot', 'completed', 'n/a', '{}', '[]', '/tmp', "
            "'2026-09-01 10:00:00', 0, 0, 1, 'keep_both', 1, 0, 0)"
        )

    command.upgrade(config, "head")

    with sqlite3.connect(db_path) as conn:
        for word in ("some", "upload*", "pilot"):
            rows = conn.execute(
                "SELECT job_id, request_id FROM jobs_fts WHERE jobs_fts MATCH ?", (word,)
            ).fetchall()
            assert rows == [("j1", "r1")], word
        assert conn.execute("SELECT file_deleted_at FROM jobs").fetchall() == [(None,)]


def test_0009_downgrades_cleanly(tmp_path: Path) -> None:
    db_path = tmp_path / "down.db"
    config = _config(db_path)
    command.upgrade(config, "head")

    command.downgrade(config, "0008")

    with sqlite3.connect(db_path) as conn:
        assert not any(name.startswith("jobs_fts") for name in _names(conn, "table"))
        assert _names(conn, "trigger") == set()
